---
fixtures:
  symlinks:
    relay: "#{source_dir}"
  repositories:
    provision: 'https://github.com/puppetlabs/provision.git'
  forge_modules:
    facts:
      repo: "puppetlabs-facts"
      ref: "1.0.0"
    inifile:
      repo: "puppetlabs-inifile"
      ref: "4.1.0"
    apt:
      repo: "puppetlabs-apt"
      ref: "7.3.0"
    puppet_agent:
      repo: "puppetlabs-puppet_agent"
      ref: "3.0.2"
    translate:
      repo: "puppetlabs-translate"
      ref: "2.1.0"
    registry:
      repo: "puppetlabs-registry"
      ref: "3.1.0"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "6.0.0"
    concat:
      repo: "puppetlabs/concat"
      ref: "6.1.0"
